### ISSUE TITLE
 display rotation

### ISSUE THREAD

**Issue by natcorvo** [crismc/homeassistant_addons#1]
### Is your feature request related to a problem?

I bought this card with display and fan.
with my vertical installation to read the information I should rotate everything by 180°
![800px-Oledhat2](https://user-images.githubusercontent.com/98548428/206024389-9934b7ca-29b3-4ab1-9e0d-0dbe4b91a231.jpg)

### Describe the solution you'd like

in the configuration options have the ability to rotate the view
![20221206_221635](https://user-images.githubusercontent.com/98548428/206025176-482efdf9-d10f-4d56-a3bc-dfb4ea32e5cc.jpg)

**Comment by crismc** [comment]
Good shout! Could certainly do with this. Should be simple enough to do. Will aim to have this in before Christmas.

**Comment by crismc** [comment]
This feature has been tested and deployed in the latest release - v1.0.3.
Thanks for the interest.
